### ISSUE TITLE
is this based on hiptext?

### ISSUE THREAD

**Issue by uwnot** [eddieantonio/imgcat#11]
hiptext does the same as this tool but it also supports videos, so what is the difference or why should we pick this one instead?

**Comment by eddieantonio** [comment]
> is this based on hiptext?

Nope!

>hiptext does the same as this tool but it also supports videos, so what is the difference or why should we pick this one instead?

This repository exists purely because I wanted to use my [kd-tree implementation](https://github.com/eddieantonio/imgcat/blob/master/src/rgbtree.c). I wrote this as a silly little hobby project. For some reason, people star and create issues, so I maintain this repo in my free time and use it to practice distributing software.

The only compelling reason to install this over hiptext is that it has fewer requirements—GNU make, a C++ compiler, and libjpeg/libpng is all that is really needed (you probably have all these). Plus, if you're on a Mac:

```
brew tap eddieantonio/eddieantonio
brew install imgcat
```
