### ISSUE TITLE
Can't display svg images on my Mac

### ISSUE THREAD

**Issue by Jeff-Tian** [eddieantonio/imgcat#33]
Not sure if it is my mac issue:

```
imgcat <(curl -s https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg)
```

it shows:

![image](https://user-images.githubusercontent.com/3367820/79818275-fd4b9980-83b9-11ea-9051-596e668b7abc.png)

For other types of image, png for example, it works.

**Comment by eddieantonio** [comment]
Since `imgcat` delegates rendering to iTerm2's [inline image protocol](https://www.iterm2.com/documentation-images.html), this issue cannot be fixed within `imgcat`. Instead, SVG rendering is an issue for iTerm2.

Please refer to this issue on iTerm2's issue tracker: https://gitlab.com/gnachman/iterm2/-/issues/6479
