### ISSUE TITLE
Python 3 is not yet supported

### ISSUE THREAD

**Issue by justijndepover** [eddieantonio/imgcat#4]
hi,

I get the following error:
```
scons install production=true
scons: *** SCons version 2.5.1 does not run under Python version 3.5.0.
Python 3 is not yet supported.
make: *** [install] Error 1
```

**Comment by eddieantonio** [comment]
Hey @justijndepover,

This is happening because the build system I used---scons---is written in Python. And it only supports Python 2.x. On systems, the default Python version is 2.x (regardless if 3.x is installed). Right now, you can work around this by making sure that `python` launches Python 2.x (probably Python 2.7) instead of whatever version it is currently using.

That said, this repo was an experiment in me using Scons and I'm not really sold on its benefits. I might switch the build system to CMake, or even plain old Makefiles to remove the Scons build dependency.

**Comment by eddieantonio** [comment]
Hello again!

The latest version removes the Scons build system. Now you can just do the following:

```sh
make install production=true
```

Let me know if this works for you!
