### ISSUE TITLE
imgcat not working!

### ISSUE THREAD

**Issue by dingye18** [eddieantonio/imgcat#41]
I'm using imgcat on my Mac mini. However, it's not working on my iterm2 after download. It only print out the symbol and numbers but the figure.
![image](https://user-images.githubusercontent.com/13417572/100407773-437d7f80-30a4-11eb-8378-b0b0a62b24db.png)

**Comment by eddieantonio** [comment]
What is the output of the following commands?

 * `which -a imgcat`
 * `printenv TERM`
 * `printenv ITERM_SESSION_ID`

**Comment by dingye18** [comment]
![image](https://user-images.githubusercontent.com/13417572/100530793-5ec9c580-3231-11eb-99a1-1ec29878d71b.png)

**Comment by dingye18** [comment]
I just found that my imgcat is not yours but the iterm2 version. However, I did `unalias imgcat` today. But it's still not working in my terminal.
![image](https://user-images.githubusercontent.com/13417572/100532763-668c6880-3237-11eb-8fac-9f05e4435d4f.png)

**Comment by eddieantonio** [comment]
Since this isn't working either this this `imgcat` or the `imgcat` bundled with iTerm2, I ask that you kindly report the issue to iTerm2's official isuse tracker: https://gitlab.com/gnachman/iterm2/-/issues

I feel like I do not have enough context to debug this for you :/

Here is a relevant issue answer that may hopefully get it working for you!

https://gitlab.com/gnachman/iterm2/-/issues/8643#note_280736730
