### ISSUE TITLE
Build failure: doesn't detect ncurses

### ISSUE THREAD

**Issue by jubalh** [eddieantonio/imgcat#47]
It seems to look for curses instead of ncurses.

```
[   17s] + ./configure --host=i586-suse-linux-gnu --build=i586-suse-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking
[   17s] checking to link with libcurses [using tigetnum()]... /usr/lib/gcc/i586-suse-linux/11/../../../../i586-suse-linux/bin/ld: cannot find -lcurses
[   17s] collect2: error: ld returned 1 exit status
[   17s] no
[   17s] ncurses is required for compilation
```

This seems to be the solution https://github.com/eddieantonio/imgcat/pull/36
But apparently we don't use autotools/configure.ac anymore. (Why is that the case?)

Full build log: https://build.opensuse.org/build/home:jubalh/openSUSE_Tumbleweed/i586/imgcat/_log

**Comment by eddieantonio** [comment]
2d56336089f0847b8d48ffd1e23b1f8de180be2b should fix it.

> But apparently we don't use autotools/configure.ac anymore. (Why is that the case?)

I guess at some point I decided I don't like autotools and tried to roll my own config script. But, obviously, rolling your own `configure` is not without its own downsides 😅

**Comment by jubalh** [comment]
> I guess at some point I decided I don't like autotools and tried to roll my own config script. But, obviously, rolling your own configure is not without its own downsides sweat_smile

Maybe should have used another build system like meson then ;)

BTW the README states:

```
Requirements

    libncurses5-dev
    GNU make
```

But libpng and libjpeg are required.
Which versions btw?

I have both libpng12-devel and libpng16-devel installed but still I get:

```
[    2s] checking to link with libncurses [using tigetnum()]... yes
[    2s] checking to link with libpng [using png_create_info_struct()]... /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: cannot find -lpng
[    2s] collect2: error: ld returned 1 exit status
[    2s] no
[    2s] checking to link with libjpeg [using jpeg_set_defaults()]... yes
```

**Comment by eddieantonio** [comment]
Alright, I updated the README.

`libpng` and `'libjpeg` are _optional_, transitive dependencies of this repo; they're optionally required by [CImg]. I'm not super sure which version, but I'm sure any decently recent version will work. I changed the build to use `pkg-config` to try to find the `libjpeg` and `libpng`. I have libpng16 and libjpeg9d, and it builds just fine 👍🏼 

> Maybe should have used another build system like meson then ;)

Originally, this repo used Scons. Then autotools. I don't really write C for more than hobby projects, so I'm not really familiar with the current up-to-date tools. I remember being frustrated both with Scons and CMake when I originally made this repo as a naïve undergraduate student, and Meson is relatively recent system. As such, I simply do not have great knowledge of C build systems.

Honestly, there are much better repos that do the same job as this repo, [some](https://github.com/wookayin/python-imgcat) [of](https://github.com/danielgatis/imgcat) [them](https://github.com/trashhalo/imgcat) are even called imgcat. I'm probably going to archive this repo soon because there are several alternatives available and because I simply don't have the incentive to maintain it :/

[CImg]: https://github.com/dtschump/CImg

**Comment by jubalh** [comment]
> Honestly, there are much better repos that do the same job as this repo, some of them are even called imgcat. I'm probably going to archive this repo soon because there are several alternatives available and because I simply don't have the incentive to maintain it :/

That's good to know because I was packaging this for openSUSE.
Will stop then :)
