### ISSUE TITLE
Can't seem to pass width or height options with ITerm2 Shell Integrations

### ISSUE THREAD

**Issue by lacostenycoder** [eddieantonio/imgcat#6]
Wasn't sure if it was related to having my shell set to ZSH so I tried in bash, passing width options worked but renders gif images as stills and they look pixelated. I'm running Iterm in xterm-256color.  But after installing shell integrations in bash I get same result so it's not shell related.

Here's output before install shell integrations, takes width param and displays pixelated but sized to width.
![screen shot 2017-04-14 at 4 51 04 am](https://cloud.githubusercontent.com/assets/6077905/25038849/c488cd26-20ce-11e7-94cb-0b8b8c6e8f20.jpg)

And here's after installing ITerm2 shell integrations.  Rejects `-w` args but shows high res gif which is animated (screen shot is still) but stays default actual image width.
Also I tried with `imgcat gify.gif -w 15` and gives exact same output with same error message.
![screen shot 2017-04-14 at 4 51 56 am](https://cloud.githubusercontent.com/assets/6077905/25038923/219a58ea-20cf-11e7-9cfa-73aa25c8c013.jpg)

**Comment by eddieantonio** [comment]
Thanks for the detailed report!

This is because the name `imgcat` is being shadowed by iTerm 2's 3.x shell integration, which _itself_ also has a program named `imgcat`, completely unrelated to this one! I have a similar setup to you:

```
~❯ echo $TERM
xterm-256color
~❯ echo $ZSH_VERSION
5.0.8
```
In iTerm, if I ask my shell where `imgcat` is, it replies:

```
~❯ which imgcat
imgcat: aliased to /Users/eddieantonio/.iterm2/imgcat
```

If I ask it for EVERYTHING named `imgcat`:

```
~❯ which -a imgcat
imgcat: aliased to /Users/eddieantonio/.iterm2/imgcat
/usr/local/bin/imgcat
```

`/usr/local/bin/imgcat` is _this_ `imgcat`, which understands the `-w` and `--no-resize` options.

---

I'm considering reimplementing iTerm 2's `imgcat` script into this repository (#2). That way, you can just unalias `imgcat`, and imgcat will both work in the chunky 256 or even 8 colour graphics modes, and in iTerm2's full-colour mode.

**Comment by eddieantonio** [comment]
The solution is to add this to the bottom of your shell's startup script:

    unalias imgcat

This will disable the shell integration's copy, and allow you to use this instead. You must upgrade to imgcat 2.0 however.

    brew upgrade imgcat
